#!/bin/bash
# @author Henry Schmale
# @date January 11, 2015
# @file install.sh
# installs the Holiday Lights System and performs default config on it

# -- Global Variables --
# project name
project="Holiday-Lights-Display-System"
# executable name
exe="HolidayLights"
# config file name
cfgFile="cfg.ini"

#declare functions
# builds the program and moves it to it's working directory
function BuildMv
{
	# make/build the program
	make
	
	# move to the install directory
	mkdir ~/$project
	mv ./$exe ~/$project
}

# set up the prgm's working directory
function SetUpDir
{
	cd ~/$project	# change to working directory
	mkdir resources
	cd resources
	mkdir songs 	# this directory holds the song data
	cd ..			# return from the resources directory
}

# generate the config file
function makeConfigFile
{
	cd ~/$project
	echo "; Config File for Holiday Lights System" >> $cfgFile
	echo "; Generated by the bash script" >> $cfgFile
}

# Main Bash script
BuildMv
echo "Finished Building The Program"
SetUpDir
echo "Finished Creating files"
#makeConfigFile
